default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>


development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "rails_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "rails_test") %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  url: <%= ENV["DATABASE_URL"] %>
  
  cable:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] %> 