name: Build, Push and Deploy

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag or use latest
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        else
          TAG=latest
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          humguyai/todo:${{ steps.vars.outputs.tag }}
          humguyai/todo:latest
        platforms: linux/amd64

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USER }}/todo
          docker pull humguyai/todo:${{ steps.vars.outputs.tag }}
          docker compose --env-file .env.production down
          docker compose --env-file .env.production up -d