name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.0.0
    branches:
      - main  # Optional: for latest tag on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        else
          TAG=latest
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          humguyai/todo:${{ steps.vars.outputs.tag }}
          humguyai/todo:latest
